export let Data = [
      {
        'bm': 'N/A',
        'c': 3,
        'cc': '45',
        'cn': '10.42',
        'createdDate': '',
        'er': 0.79,
        'm6': '-5.00',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 636,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '0.2 % on or before 6 Months<br/> Nil after 6 Months<br/>',
        'sm': '1,000.00',
        'sn': 'DSP Bond Fund-Reg(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 45,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '0.19',
        'y3': '3.57',
        'y5': '4.70'
      },
      {
        'bm': 'N/A',
        'c': 3,
        'cc': '45',
        'cn': '55.44',
        'createdDate': '',
        'er': 0.79,
        'm6': '-3.06',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 637,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '0.2 % on or before 6 Months<br/> Nil after 6 Months<br/>',
        'sm': '1,000.00',
        'sn': 'DSP Bond Fund-Reg(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 45,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '1.17',
        'y3': '5.36',
        'y5': '6.80'
      },
      {
        'bm': 'N/A',
        'c': 3,
        'cc': '45',
        'cn': '10.50',
        'createdDate': '',
        'er': 0.79,
        'm6': '-4.98',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 638,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '0.2 % on or before 6 Months<br/> Nil after 6 Months<br/>',
        'sm': '1,000.00',
        'sn': 'DSP Bond Fund-Reg(MDR)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 45,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '-0.23',
        'y3': '3.42',
        'y5': '4.71'
      },
      {
        'bm': 'NIFTY 500 - TRI',
        'c': 4,
        'cc': '49',
        'cn': '45.11',
        'createdDate': '',
        'er': 2.36,
        'm6': '13.79',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 641,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 12 Months<br/> Nil after 12 Months<br/>',
        'sm': '1,000.00',
        'sn': 'DSP Equity Fund-Reg(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 49,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '5.25',
        'y3': '13.99',
        'y5': '10.92'
      },
      {
        'bm': 'NIFTY 500 - TRI',
        'c': 4,
        'cc': '49',
        'cn': '40.24',
        'createdDate': '',
        'er': 2.36,
        'm6': '15.30',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 642,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 12 Months<br/> Nil after 12 Months<br/>',
        'sm': '1,000.00',
        'sn': 'DSP Equity Fund-Reg(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 49,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '6.65',
        'y3': '14.50',
        'y5': '11.21'
      },
      {
        'bm': 'N/A',
        'c': 3,
        'cc': '46',
        'cn': '10.76',
        'createdDate': '',
        'er': 1.05,
        'm6': '9.98',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 691,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'DSP G-Sec Fund-Reg(MD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 46,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '9.80',
        'y3': '6.16',
        'y5': '6.44'
      },
      {
        'bm': 'N/A',
        'c': 3,
        'cc': '46',
        'cn': '12.38',
        'createdDate': '',
        'er': 1.05,
        'm6': '10.03',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 692,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'DSP G-Sec Fund-Reg(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 46,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '10.55',
        'y3': '6.42',
        'y5': '6.71'
      },
      {
        'bm': 'N/A',
        'c': 3,
        'cc': '46',
        'cn': '61.27',
        'createdDate': '',
        'er': 1.05,
        'm6': '13.46',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 693,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'DSP G-Sec Fund-Reg(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 46,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '12.34',
        'y3': '8.41',
        'y5': '8.76'
      },
      {
        'bm': 'S&P BSE 500 - TRI',
        'c': 4,
        'cc': '49',
        'cn': '30.62',
        'createdDate': '',
        'er': 2.08,
        'm6': '7.42',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 902,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil upto 1 % of units and 1% for above the limits on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'L&T Equity Fund-Reg(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 49,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '-0.89',
        'y3': '10.78',
        'y5': '9.96'
      },
      {
        'bm': 'S&P BSE 500 - TRI',
        'c': 4,
        'cc': '49',
        'cn': '83.61',
        'createdDate': '',
        'er': 2.08,
        'm6': '8.43',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 903,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil upto 1 % of units and 1% for above the limits on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'L&T Equity Fund-Reg(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 49,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '0.05',
        'y3': '11.14',
        'y5': '10.18'
      },
      {
        'bm': 'NIFTY 100 - TRI',
        'c': 4,
        'cc': '31',
        'cn': '38.15',
        'createdDate': '',
        'er': 1.84,
        'm6': '8.96',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 930,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year',
        'sm': '1,000.00',
        'sn': 'Franklin India Bluechip Fund(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 31,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '2.35',
        'y3': '8.44',
        'y5': '9.19'
      },
      {
        'bm': 'NIFTY 100 - TRI',
        'c': 4,
        'cc': '31',
        'cn': '471.28',
        'createdDate': '',
        'er': 1.84,
        'm6': '10.09',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 931,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year',
        'sm': '1,000.00',
        'sn': 'Franklin India Bluechip Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 31,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '3.41',
        'y3': '8.81',
        'y5': '9.41'
      },
      {
        'bm': 'Nifty LargeMidcap 250 Index',
        'c': 4,
        'cc': '61',
        'cn': '15.44',
        'createdDate': '',
        'er': 2.07,
        'm6': '7.34',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 932,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year',
        'sm': '1,000.00',
        'sn': 'Franklin India Equity Advantage Fund(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 61,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '-1.49',
        'y3': '8.45',
        'y5': '10.16'
      },
      {
        'bm': 'Nifty LargeMidcap 250 Index',
        'c': 4,
        'cc': '61',
        'cn': '80.90',
        'createdDate': '',
        'er': 2.07,
        'm6': '8.46',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 933,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year',
        'sm': '1,000.00',
        'sn': 'Franklin India Equity Advantage Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 61,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '-0.47',
        'y3': '8.82',
        'y5': '10.39'
      },
      {
        'bm': 'NIFTY 500 - TRI',
        'c': 4,
        'cc': '63',
        'cn': '25.30',
        'createdDate': '',
        'er': 1.82,
        'm6': '18.05',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 937,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year',
        'sm': '1,000.00',
        'sn': 'Franklin India Focused Equity Fund(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 63,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '9.81',
        'y3': '12.89',
        'y5': '15.02'
      },
      {
        'bm': 'NIFTY 500 - TRI',
        'c': 4,
        'cc': '63',
        'cn': '43.03',
        'createdDate': '',
        'er': 1.82,
        'm6': '18.05',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 938,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year',
        'sm': '1,000.00',
        'sn': 'Franklin India Focused Equity Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 63,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '10.92',
        'y3': '13.27',
        'y5': '15.25'
      },
      {
        'bm': 'NIFTY 500 - TRI',
        'c': 4,
        'cc': '49',
        'cn': '36.51',
        'createdDate': '',
        'er': 1.77,
        'm6': '8.36',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 949,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year',
        'sm': '1,000.00',
        'sn': 'Franklin India Equity Fund(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 49,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '1.39',
        'y3': '9.00',
        'y5': '12.14'
      },
      {
        'bm': 'NIFTY 500 - TRI',
        'c': 4,
        'cc': '49',
        'cn': '597.92',
        'createdDate': '',
        'er': 1.77,
        'm6': '9.30',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 950,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year',
        'sm': '1,000.00',
        'sn': 'Franklin India Equity Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 49,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '2.27',
        'y3': '9.32',
        'y5': '12.33'
      },
      {
        'bm': 'Nifty Smallcap 250 - TRI',
        'c': 4,
        'cc': '33',
        'cn': '24.63',
        'createdDate': '',
        'er': 1.87,
        'm6': '7.75',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 951,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year',
        'sm': '1,000.00',
        'sn': 'Franklin India Smaller Cos Fund(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 33,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '-8.78',
        'y3': '8.09',
        'y5': '14.50'
      },
      {
        'bm': 'Nifty Smallcap 250 - TRI',
        'c': 4,
        'cc': '33',
        'cn': '54.42',
        'createdDate': '',
        'er': 1.87,
        'm6': '8.69',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 952,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year',
        'sm': '1,000.00',
        'sn': 'Franklin India Smaller Cos Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 33,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '-7.98',
        'y3': '8.41',
        'y5': '14.70'
      },
      {
        'bm': 'NIFTY 500 - TRI',
        'c': 4,
        'cc': '8',
        'cn': '41.68',
        'createdDate': '',
        'er': 1.93,
        'm6': '9.22',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 956,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '500.00',
        'sn': 'Franklin India Taxshield(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 8,
        'vn': 4,
        'vr': 3,
        'wl': 0,
        'y1': '1.36',
        'y3': '9.52',
        'y5': '12.26'
      },
      {
        'bm': 'NIFTY 500 - TRI',
        'c': 4,
        'cc': '8',
        'cn': '578.51',
        'createdDate': '',
        'er': 1.93,
        'm6': '10.35',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 957,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '500.00',
        'sn': 'Franklin India Taxshield(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 8,
        'vn': 4,
        'vr': 3,
        'wl': 0,
        'y1': '2.41',
        'y3': '9.90',
        'y5': '12.49'
      },
      {
        'bm': 'CRISIL Hybrid 35+65 - Aggressive Index',
        'c': 4,
        'cc': '12',
        'cn': '20.89',
        'createdDate': '',
        'er': 2.12,
        'm6': '8.51',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 998,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil upto 1 % of units on or before 1 Year<br/> For excess units 1% on or before 1 Year & Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'Franklin India Equity Hybrid Fund(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 12,
        'vn': 6,
        'vr': 3,
        'wl': 0,
        'y1': '3.69',
        'y3': '8.61',
        'y5': '11.43'
      },
      {
        'bm': 'CRISIL Hybrid 35+65 - Aggressive Index',
        'c': 4,
        'cc': '12',
        'cn': '122.21',
        'createdDate': '',
        'er': 2.12,
        'm6': '9.50',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 999,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil upto 1 % of units on or before 1 Year<br/> For excess units 1% on or before 1 Year & Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'Franklin India Equity Hybrid Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 12,
        'vn': 6,
        'vr': 3,
        'wl': 0,
        'y1': '4.63',
        'y3': '8.94',
        'y5': '11.63'
      },
      {
        'bm': 'N/A',
        'c': 1,
        'cc': '24',
        'cn': '1,001.08',
        'createdDate': '',
        'er': 0.12,
        'm6': '5.07',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 1031,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'IDFC Cash Fund-Reg(DD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 24,
        'vn': 9,
        'vr': 3,
        'wl': 0,
        'y1': '5.23',
        'y3': '5.00',
        'y5': '5.46'
      },
      {
        'bm': 'N/A',
        'c': 1,
        'cc': '24',
        'cn': '2,288.33',
        'createdDate': '',
        'er': 0.12,
        'm6': '7.07',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 1032,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'IDFC Cash Fund-Reg(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 24,
        'vn': 9,
        'vr': 3,
        'wl': 0,
        'y1': '7.34',
        'y3': '7.02',
        'y5': '7.60'
      },
      {
        'bm': 'N/A',
        'c': 1,
        'cc': '24',
        'cn': '1,002.54',
        'createdDate': '',
        'er': 0.12,
        'm6': '5.06',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 1033,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'IDFC Cash Fund-Reg(MD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 24,
        'vn': 9,
        'vr': 3,
        'wl': 0,
        'y1': '5.24',
        'y3': '5.01',
        'y5': '5.46'
      },
      {
        'bm': 'N/A',
        'c': 1,
        'cc': '24',
        'cn': '1,001.80',
        'createdDate': '',
        'er': 0.12,
        'm6': '5.07',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 1034,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'IDFC Cash Fund-Reg(WD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 24,
        'vn': 9,
        'vr': 3,
        'wl': 0,
        'y1': '5.24',
        'y3': '5.00',
        'y5': '5.46'
      },
      {
        'bm': 'N/A',
        'c': 3,
        'cc': '68',
        'cn': '11.88',
        'createdDate': '',
        'er': 1.72,
        'm6': '8.37',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1082,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil for 1 % of investment and 1% for remaining investment on or before 365 Days<br/> Nil after 365 Days<br/>',
        'sm': '1,000.00',
        'sn': 'IDFC Bond Fund - Income Plan-Reg(HD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 68,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '9.82',
        'y3': '5.87',
        'y5': '6.26'
      },
      {
        'bm': 'N/A',
        'c': 3,
        'cc': '68',
        'cn': '45.59',
        'createdDate': '',
        'er': 1.72,
        'm6': '11.61',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1090,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil for 1 % of investment and 1% for remaining investment on or before 365 Days<br/> Nil after 365 Days<br/>',
        'sm': '1,000.00',
        'sn': 'IDFC Bond Fund - Income Plan-Reg(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 68,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '11.52',
        'y3': '7.81',
        'y5': '8.40'
      },
      {
        'bm': 'N/A',
        'c': 3,
        'cc': '68',
        'cn': '11.65',
        'createdDate': '',
        'er': 1.72,
        'm6': '7.46',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1091,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil for 1 % of investment and 1% for remaining investment on or before 365 Days<br/> Nil after 365 Days<br/>',
        'sm': '1,000.00',
        'sn': 'IDFC Bond Fund - Income Plan-Reg(AD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 68,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '9.34',
        'y3': '5.97',
        'y5': '4.76'
      },
      {
        'bm': 'N/A',
        'c': 3,
        'cc': '68',
        'cn': '11.97',
        'createdDate': '',
        'er': 1.72,
        'm6': '8.72',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1092,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil for 1 % of investment and 1% for remaining investment on or before 365 Days<br/> Nil after 365 Days<br/>',
        'sm': '1,000.00',
        'sn': 'IDFC Bond Fund - Income Plan-Reg(QD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 68,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '10.01',
        'y3': '5.80',
        'y5': '6.24'
      },
      {
        'bm': 'NIFTY 500 - TRI',
        'c': 4,
        'cc': '49',
        'cn': '52.40',
        'createdDate': '',
        'er': 1.79,
        'm6': '14.10',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1130,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'HDFC Equity Fund(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 49,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '11.49',
        'y3': '14.79',
        'y5': '10.02'
      },
      {
        'bm': 'NIFTY 500 - TRI',
        'c': 4,
        'cc': '49',
        'cn': '693.53',
        'createdDate': '',
        'er': 1.79,
        'm6': '15.45',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1131,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'HDFC Equity Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 49,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '12.81',
        'y3': '15.24',
        'y5': '10.28'
      },
      {
        'bm': 'Crisil Gilt Index',
        'c': 3,
        'cc': '46',
        'cn': '11.40',
        'createdDate': '',
        'er': 0.9,
        'm6': '7.71',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1268,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'HDFC Gilt Fund(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 46,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '8.29',
        'y3': '5.25',
        'y5': '6.49'
      },
      {
        'bm': 'Crisil Gilt Index',
        'c': 3,
        'cc': '46',
        'cn': '37.97',
        'createdDate': '',
        'er': 0.9,
        'm6': '9.51',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1269,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'HDFC Gilt Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 46,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '9.61',
        'y3': '7.16',
        'y5': '8.73'
      },
      {
        'bm': 'N/A',
        'c': 3,
        'cc': '45',
        'cn': '10.58',
        'createdDate': '',
        'er': 1.29,
        'm6': '6.68',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1277,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'HDFC Medium Term Debt Fund(FD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 45,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '6.30',
        'y3': '5.39',
        'y5': '5.71'
      },
      {
        'bm': 'N/A',
        'c': 3,
        'cc': '45',
        'cn': '37.47',
        'createdDate': '',
        'er': 1.29,
        'm6': '9.50',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1278,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'HDFC Medium Term Debt Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 45,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '8.51',
        'y3': '7.54',
        'y5': '7.97'
      },
      {
        'bm': 'N/A',
        'c': 1,
        'cc': '24',
        'cn': '1,019.82',
        'createdDate': '',
        'er': 0.25,
        'm6': '5.21',
        'mi': '10,000.00',
        'nr': 1,
        'sc': 1285,
        'schemeCode': 0,
        'schemeName': '',
        'si': 0,
        'sl': 'Nil',
        'sm': '5,000.00',
        'sn': 'HDFC Liquid Fund(DD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 24,
        'vn': 9,
        'vr': 3,
        'wl': 0,
        'y1': '5.28',
        'y3': '5.00',
        'y5': '5.44'
      },
      {
        'bm': 'N/A',
        'c': 1,
        'cc': '24',
        'cn': '3,711.95',
        'createdDate': '',
        'er': 0.25,
        'm6': '7.27',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1286,
        'schemeCode': 0,
        'schemeName': '',
        'si': 0,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'HDFC Liquid Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 24,
        'vn': 9,
        'vr': 3,
        'wl': 0,
        'y1': '7.41',
        'y3': '6.99',
        'y5': '7.58'
      },
      {
        'bm': 'N/A',
        'c': 1,
        'cc': '24',
        'cn': '1,029.29',
        'createdDate': '',
        'er': 0.25,
        'm6': '5.21',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1287,
        'schemeCode': 0,
        'schemeName': '',
        'si': 0,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'HDFC Liquid Fund(MD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 24,
        'vn': 9,
        'vr': 3,
        'wl': 0,
        'y1': '5.29',
        'y3': '5.00',
        'y5': '5.45'
      },
      {
        'bm': 'N/A',
        'c': 1,
        'cc': '24',
        'cn': '1,031.21',
        'createdDate': '',
        'er': 0.25,
        'm6': '5.21',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1293,
        'schemeCode': 0,
        'schemeName': '',
        'si': 0,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'HDFC Liquid Fund(WD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 24,
        'vn': 9,
        'vr': 3,
        'wl': 0,
        'y1': '5.29',
        'y3': '5.00',
        'y5': '5.46'
      },
      {
        'bm': 'NIFTY 50 Hybrid Composite Debt 15:85 Index',
        'c': 4,
        'cc': '14',
        'cn': '46.37',
        'createdDate': '',
        'er': 1.8,
        'm6': '12.53',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1298,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil for 1 % of investment and 1% for remaining Investment on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'HDFC Hybrid Debt Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 14,
        'vn': 7,
        'vr': 3,
        'wl': 0,
        'y1': '8.06',
        'y3': '8.02',
        'y5': '7.90'
      },
      {
        'bm': 'NIFTY 50 Hybrid Composite Debt 15:85 Index',
        'c': 4,
        'cc': '14',
        'cn': '13.12',
        'createdDate': '',
        'er': 1.8,
        'm6': '9.53',
        'mi': '25,000.00',
        'nr': 1,
        'sc': 1299,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil for 1 % of investment and 1% for remaining Investment on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'HDFC Hybrid Debt Fund(MD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 14,
        'vn': 7,
        'vr': 3,
        'wl': 0,
        'y1': '5.07',
        'y3': '5.19',
        'y5': '5.20'
      },
      {
        'bm': 'NIFTY 50 Hybrid Composite Debt 15:85 Index',
        'c': 4,
        'cc': '14',
        'cn': '13.96',
        'createdDate': '',
        'er': 1.8,
        'm6': '9.72',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1300,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil for 1 % of investment and 1% for remaining Investment on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'HDFC Hybrid Debt Fund(QD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 14,
        'vn': 7,
        'vr': 3,
        'wl': 0,
        'y1': '5.24',
        'y3': '5.33',
        'y5': '5.34'
      },
      {
        'bm': 'N/A',
        'c': 4,
        'cc': '57',
        'cn': '11.26',
        'createdDate': '',
        'er': 1.96,
        'm6': '6.11',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1308,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'NIL upto 1 % of investment and 1% in excess of 1 % of investment on or before 1 Year<br/> NIL after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'HDFC Equity Savings Fund(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 57,
        'vn': 8,
        'vr': 3,
        'wl': 0,
        'y1': '5.45',
        'y3': '10.26',
        'y5': '7.46'
      },
      {
        'bm': 'N/A',
        'c': 4,
        'cc': '57',
        'cn': '37.28',
        'createdDate': '',
        'er': 1.96,
        'm6': '6.65',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1309,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'NIL upto 1 % of investment and 1% in excess of 1 % of investment on or before 1 Year<br/> NIL after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'HDFC Equity Savings Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 57,
        'vn': 8,
        'vr': 3,
        'wl': 0,
        'y1': '6.51',
        'y3': '10.64',
        'y5': '8.26'
      },
      {
        'bm': 'N/A',
        'c': 1,
        'cc': '24',
        'cn': '1,000.95',
        'createdDate': '',
        'er': 0.14,
        'm6': '5.29',
        'mi': '5,000.00',
        'nr': 0,
        'sc': 1339,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'HSBC Cash Fund(DD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 24,
        'vn': 9,
        'vr': 3,
        'wl': 0,
        'y1': '5.40',
        'y3': '5.09',
        'y5': '5.50'
      },
      {
        'bm': 'N/A',
        'c': 1,
        'cc': '24',
        'cn': '1,882.83',
        'createdDate': '',
        'er': 0.14,
        'm6': '7.36',
        'mi': '5,000.00',
        'nr': 0,
        'sc': 1340,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'HSBC Cash Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 24,
        'vn': 9,
        'vr': 3,
        'wl': 0,
        'y1': '7.57',
        'y3': '7.12',
        'y5': '7.64'
      },
      {
        'bm': 'N/A',
        'c': 1,
        'cc': '24',
        'cn': '1,003.71',
        'createdDate': '',
        'er': 0.14,
        'm6': '5.29',
        'mi': '5,000.00',
        'nr': 0,
        'sc': 1341,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'HSBC Cash Fund(MD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 24,
        'vn': 9,
        'vr': 3,
        'wl': 0,
        'y1': '5.39',
        'y3': '5.09',
        'y5': '5.50'
      },
      {
        'bm': 'N/A',
        'c': 1,
        'cc': '24',
        'cn': '1,111.97',
        'createdDate': '',
        'er': 0.14,
        'm6': '5.27',
        'mi': '5,000.00',
        'nr': 0,
        'sc': 1342,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'HSBC Cash Fund(WD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 24,
        'vn': 9,
        'vr': 3,
        'wl': 0,
        'y1': '5.40',
        'y3': '5.10',
        'y5': '5.49'
      },
      {
        'bm': 'NIFTY 50 - TRI',
        'c': 4,
        'cc': '31',
        'cn': '29.53',
        'createdDate': '',
        'er': 2.43,
        'm6': '12.62',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1347,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'HSBC Large Cap Equity Fund(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 31,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '4.48',
        'y3': '12.20',
        'y5': '8.52'
      },
      {
        'bm': 'NIFTY 50 - TRI',
        'c': 4,
        'cc': '31',
        'cn': '215.50',
        'createdDate': '',
        'er': 2.43,
        'm6': '13.53',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1348,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'HSBC Large Cap Equity Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 31,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '5.34',
        'y3': '12.51',
        'y5': '8.72'
      },
      {
        'bm': 'S&P BSE 200 - TRI',
        'c': 4,
        'cc': '49',
        'cn': '86.39',
        'createdDate': '',
        'er': 2.48,
        'm6': '9.71',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1441,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'HSBC Multi Cap Equity Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 49,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '-1.96',
        'y3': '9.21',
        'y5': '9.64'
      },
      {
        'bm': 'S&P BSE 200 - TRI',
        'c': 4,
        'cc': '8',
        'cn': '20.70',
        'createdDate': '',
        'er': 2.43,
        'm6': '10.68',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 1461,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '500.00',
        'sn': 'HSBC Tax Saver Equity Fund(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 8,
        'vn': 4,
        'vr': 3,
        'wl': 0,
        'y1': '0.31',
        'y3': '10.66',
        'y5': '10.20'
      },
      {
        'bm': 'S&P BSE 200 - TRI',
        'c': 4,
        'cc': '8',
        'cn': '37.64',
        'createdDate': '',
        'er': 2.43,
        'm6': '11.77',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 1462,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '500.00',
        'sn': 'HSBC Tax Saver Equity Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 8,
        'vn': 4,
        'vr': 3,
        'wl': 0,
        'y1': '1.30',
        'y3': '11.02',
        'y5': '10.40'
      },
      {
        'bm': 'NIFTY 50 Hybrid Composite Debt 65:35 Index',
        'c': 4,
        'cc': '76',
        'cn': '144.96',
        'createdDate': '',
        'er': 2.55,
        'm6': '24.16',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1489,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'ICICI Pru Child Care Fund-Gift Plan',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 76,
        'vn': 10,
        'vr': 3,
        'wl': 0,
        'y1': '7.99',
        'y3': '11.30',
        'y5': '9.82'
      },
      {
        'bm': 'Nifty Midcap 150 - TRI',
        'c': 4,
        'cc': '32',
        'cn': '23.04',
        'createdDate': '',
        'er': 2.35,
        'm6': '6.50',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1498,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'ICICI Pru Midcap Fund(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 32,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '-3.95',
        'y3': '11.94',
        'y5': '12.30'
      },
      {
        'bm': 'Nifty Midcap 150 - TRI',
        'c': 4,
        'cc': '32',
        'cn': '95.95',
        'createdDate': '',
        'er': 2.35,
        'm6': '6.48',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1499,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'ICICI Pru Midcap Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 32,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '-3.46',
        'y3': '12.11',
        'y5': '12.37'
      },
      {
        'bm': 'NIFTY Low Duration Debt Index',
        'c': 2,
        'cc': '66',
        'cn': '364.33',
        'createdDate': '',
        'er': 0.45,
        'm6': '8.83',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 1500,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'ICICI Pru Savings Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 66,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '8.55',
        'y3': '7.78',
        'y5': '8.24'
      },
      {
        'bm': 'NIFTY Low Duration Debt Index',
        'c': 2,
        'cc': '66',
        'cn': '105.44',
        'createdDate': '',
        'er': 0.45,
        'm6': '6.27',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 1501,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'ICICI Pru Savings Fund(WD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 66,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '6.08',
        'y3': '5.55',
        'y5': '5.92'
      },
      {
        'bm': 'NIFTY Low Duration Debt Index',
        'c': 2,
        'cc': '66',
        'cn': '105.71',
        'createdDate': '',
        'er': 0.45,
        'm6': '6.30',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 1502,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'ICICI Pru Savings Fund(DD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 66,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '6.08',
        'y3': '5.55',
        'y5': '5.91'
      },
      {
        'bm': 'Nifty LargeMidcap 250 Index - TRI',
        'c': 4,
        'cc': '61',
        'cn': '16.44',
        'createdDate': '',
        'er': 2.09,
        'm6': '9.55',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1607,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Month<br/> Nil after 1 Month<br/>',
        'sm': '1,000.00',
        'sn': 'ICICI Pru Large & Mid Cap Fund(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 61,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '3.14',
        'y3': '11.18',
        'y5': '8.60'
      },
      {
        'bm': 'Nifty LargeMidcap 250 Index - TRI',
        'c': 4,
        'cc': '61',
        'cn': '331.87',
        'createdDate': '',
        'er': 2.09,
        'm6': '10.59',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1608,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Month<br/> Nil after 1 Month<br/>',
        'sm': '1,000.00',
        'sn': 'ICICI Pru Large & Mid Cap Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 61,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '4.14',
        'y3': '11.64',
        'y5': '8.82'
      },
      {
        'bm': 'NIFTY Long Duration Debt Index',
        'c': 3,
        'cc': '18',
        'cn': '61.05',
        'createdDate': '',
        'er': 1.7,
        'm6': '13.99',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1617,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'ICICI Pru Long Term Bond Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 18,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '13.48',
        'y3': '8.86',
        'y5': '9.12'
      },
      {
        'bm': 'NIFTY Long Duration Debt Index',
        'c': 3,
        'cc': '18',
        'cn': '11.42',
        'createdDate': '',
        'er': 1.7,
        'm6': '10.17',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1618,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'ICICI Pru Long Term Bond Fund(HD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 18,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '11.46',
        'y3': '6.69',
        'y5': '6.67'
      },
      {
        'bm': 'NIFTY Long Duration Debt Index',
        'c': 3,
        'cc': '18',
        'cn': '12.29',
        'createdDate': '',
        'er': 1.7,
        'm6': '10.10',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1621,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'ICICI Pru Long Term Bond Fund(QD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 18,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '11.42',
        'y3': '6.64',
        'y5': '6.47'
      },
      {
        'bm': 'NIFTY 50 - TRI',
        'c': 4,
        'cc': '7',
        'cn': '115.30',
        'createdDate': '',
        'er': 0.45,
        'm6': '13.79',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1623,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'ICICI Pru Nifty Index Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 7,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '11.02',
        'y3': '13.62',
        'y5': '9.62'
      },
      {
        'bm': 'N/A',
        'c': 3,
        'cc': '16',
        'cn': '39.26',
        'createdDate': '',
        'er': 1.15,
        'm6': '9.86',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1682,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'ICICI Pru Short Term Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 16,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '8.78',
        'y3': '7.61',
        'y5': '8.19'
      },
      {
        'bm': 'N/A',
        'c': 3,
        'cc': '16',
        'cn': '12.14',
        'createdDate': '',
        'er': 1.15,
        'm6': '6.95',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1683,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'ICICI Pru Short Term Fund(MD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 16,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '6.18',
        'y3': '5.39',
        'y5': '5.95'
      },
      {
        'bm': 'N/A',
        'c': 3,
        'cc': '16',
        'cn': '12.33',
        'createdDate': '',
        'er': 1.15,
        'm6': '7.19',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1684,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'ICICI Pru Short Term Fund(FD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 16,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '6.34',
        'y3': '5.51',
        'y5': '6.01'
      },
      {
        'bm': 'S&P BSE 200 - TRI',
        'c': 4,
        'cc': '62',
        'cn': '22.66',
        'createdDate': '',
        'er': 2.45,
        'm6': '12.75',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1848,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 60 Days',
        'sm': '1,000.00',
        'sn': 'JM Value Fund(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 62,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '2.30',
        'y3': '14.42',
        'y5': '12.56'
      },
      {
        'bm': 'S&P BSE 200 - TRI',
        'c': 4,
        'cc': '62',
        'cn': '32.45',
        'createdDate': '',
        'er': 2.45,
        'm6': '12.75',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1849,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 60 Days',
        'sm': '1,000.00',
        'sn': 'JM Value Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 62,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '2.30',
        'y3': '14.42',
        'y5': '12.56'
      },
      {
        'bm': 'S&P BSE 200 - TRI',
        'c': 4,
        'cc': '61',
        'cn': '16.77',
        'createdDate': '',
        'er': 2.54,
        'm6': '10.92',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1955,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 12 Months<br/> Nil after 12 Months<br/>',
        'sm': '1,000.00',
        'sn': 'Edelweiss Large & Mid Cap Fund-Reg(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 61,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '4.06',
        'y3': '11.73',
        'y5': '10.63'
      },
      {
        'bm': 'S&P BSE 200 - TRI',
        'c': 4,
        'cc': '61',
        'cn': '31.95',
        'createdDate': '',
        'er': 2.54,
        'm6': '11.27',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1956,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 12 Months<br/> Nil after 12 Months<br/>',
        'sm': '1,000.00',
        'sn': 'Edelweiss Large & Mid Cap Fund-Reg(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 61,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '4.89',
        'y3': '12.02',
        'y5': '10.80'
      },
      {
        'bm': 'NIFTY 50 - TRI',
        'c': 4,
        'cc': '31',
        'cn': '35.02',
        'createdDate': '',
        'er': 2.18,
        'm6': '12.65',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 1961,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'Kotak Bluechip Fund(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 31,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '6.87',
        'y3': '10.75',
        'y5': '10.99'
      },
      {
        'bm': 'NIFTY 50 - TRI',
        'c': 4,
        'cc': '31',
        'cn': '240.19',
        'createdDate': '',
        'er': 2.18,
        'm6': '13.04',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 1962,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'Kotak Bluechip Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 31,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '7.23',
        'y3': '10.93',
        'y5': '11.10'
      },
      {
        'bm': 'Nifty Short Duration Debt Index',
        'c': 2,
        'cc': '16',
        'cn': '10.21',
        'createdDate': '',
        'er': 1.14,
        'm6': '7.29',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1970,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'Kotak Bond-STP(MD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 16,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '6.75',
        'y3': '5.25',
        'y5': '5.61'
      },
      {
        'bm': 'Nifty Short Duration Debt Index',
        'c': 2,
        'cc': '16',
        'cn': '35.38',
        'createdDate': '',
        'er': 1.14,
        'm6': '9.93',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1971,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'Kotak Bond-STP(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 16,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '9.00',
        'y3': '7.28',
        'y5': '7.79'
      },
      {
        'bm': 'NIFTY Ultra Short Duration Debt Index',
        'c': 2,
        'cc': '17',
        'cn': '30.42',
        'createdDate': '',
        'er': 0.68,
        'm6': '8.46',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1995,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'Kotak Savings Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 17,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '8.18',
        'y3': '7.46',
        'y5': '7.93'
      },
      {
        'bm': 'NIFTY Ultra Short Duration Debt Index',
        'c': 2,
        'cc': '17',
        'cn': '10.47',
        'createdDate': '',
        'er': 0.68,
        'm6': '6.68',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1996,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'Kotak Savings Fund(MD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 17,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '6.45',
        'y3': '5.63',
        'y5': '5.90'
      },
      {
        'bm': 'NIFTY Ultra Short Duration Debt Index',
        'c': 2,
        'cc': '17',
        'cn': '10.20',
        'createdDate': '',
        'er': 0.68,
        'm6': '6.14',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 1997,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'Kotak Savings Fund(WD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 17,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '5.86',
        'y3': '5.35',
        'y5': '5.74'
      },
      {
        'bm': 'CRISIL Hybrid 85+15 - Conservative Index',
        'c': 3,
        'cc': '14',
        'cn': '31.33',
        'createdDate': '',
        'er': 2.21,
        'm6': '13.60',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 2051,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil for 1 % of investment and 1% for remaining Investment on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'Kotak Debt Hybrid Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 14,
        'vn': 7,
        'vr': 3,
        'wl': 0,
        'y1': '6.70',
        'y3': '7.62',
        'y5': '8.42'
      },
      {
        'bm': 'CRISIL Hybrid 85+15 - Conservative Index',
        'c': 3,
        'cc': '14',
        'cn': '11.83',
        'createdDate': '',
        'er': 2.21,
        'm6': '10.66',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 2052,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil for 1 % of investment and 1% for remaining Investment on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'Kotak Debt Hybrid Fund(MD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 14,
        'vn': 7,
        'vr': 3,
        'wl': 0,
        'y1': '3.78',
        'y3': '5.01',
        'y5': '6.00'
      },
      {
        'bm': 'CRISIL Hybrid 85+15 - Conservative Index',
        'c': 3,
        'cc': '14',
        'cn': '13.42',
        'createdDate': '',
        'er': 2.21,
        'm6': '11.21',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 2053,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil for 1 % of investment and 1% for remaining Investment on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'Kotak Debt Hybrid Fund(QD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 14,
        'vn': 7,
        'vr': 3,
        'wl': 0,
        'y1': '4.29',
        'y3': '5.46',
        'y5': '6.45'
      },
      {
        'bm': 'Nifty Smallcap 50 - TRI',
        'c': 4,
        'cc': '33',
        'cn': '36.10',
        'createdDate': '',
        'er': 2.15,
        'm6': '8.44',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 2065,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'Kotak Small Cap Fund(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 33,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '-7.22',
        'y3': '8.75',
        'y5': '13.42'
      },
      {
        'bm': 'Nifty Smallcap 50 - TRI',
        'c': 4,
        'cc': '33',
        'cn': '72.10',
        'createdDate': '',
        'er': 2.15,
        'm6': '8.81',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 2066,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'Kotak Small Cap Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 33,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '-6.89',
        'y3': '8.88',
        'y5': '13.52'
      },
      {
        'bm': 'NIFTY 500 - TRI',
        'c': 4,
        'cc': '8',
        'cn': '19.62',
        'createdDate': '',
        'er': 2.55,
        'm6': '13.60',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 2074,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '500.00',
        'sn': 'Kotak Tax Saver Scheme(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 8,
        'vn': 4,
        'vr': 3,
        'wl': 0,
        'y1': '10.96',
        'y3': '14.21',
        'y5': '13.83'
      },
      {
        'bm': 'NIFTY 500 - TRI',
        'c': 4,
        'cc': '8',
        'cn': '45.88',
        'createdDate': '',
        'er': 2.55,
        'm6': '14.12',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 2075,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '500.00',
        'sn': 'Kotak Tax Saver Scheme(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 8,
        'vn': 4,
        'vr': 3,
        'wl': 0,
        'y1': '12.00',
        'y3': '14.57',
        'y5': '14.04'
      },
      {
        'bm': 'CRISIL Low Duration Debt Index',
        'c': 3,
        'cc': '66',
        'cn': '9.62',
        'createdDate': '',
        'er': 0.83,
        'm6': '-7.60',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 2148,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 3 Months<br/> 0.5 % Betweem 3 Months and 6 Months<br/> Nil after 6 Months<br/>',
        'sm': '1,000.00',
        'sn': 'LIC MF Savings Fund(MD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'F',
        'tc': 1,
        'tot': '',
        'vc': 66,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '-1.00',
        'y3': '2.98',
        'y5': '4.14'
      },
      {
        'bm': 'CRISIL Low Duration Debt Index',
        'c': 3,
        'cc': '66',
        'cn': '26.98',
        'createdDate': '',
        'er': 0.83,
        'm6': '-6.13',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 2149,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '1% on or before 3 Months<br/> 0.5 % Betweem 3 Months and 6 Months<br/> Nil after 6 Months<br/>',
        'sm': '1,000.00',
        'sn': 'LIC MF Savings Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 66,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '0.64',
        'y3': '4.83',
        'y5': '6.11'
      },
      {
        'bm': 'S&P BSE SENSEX - TRI',
        'c': 4,
        'cc': '8',
        'cn': '17.72',
        'createdDate': '',
        'er': 2.58,
        'm6': '9.45',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 2152,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '500.00',
        'sn': 'LIC MF Tax Plan(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'F',
        'tc': 1,
        'tot': '',
        'vc': 8,
        'vn': 4,
        'vr': 3,
        'wl': 0,
        'y1': '4.25',
        'y3': '12.54',
        'y5': '11.88'
      },
      {
        'bm': 'S&P BSE SENSEX - TRI',
        'c': 4,
        'cc': '8',
        'cn': '68.13',
        'createdDate': '',
        'er': 2.58,
        'm6': '9.87',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 2153,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil',
        'sm': '1,000.00',
        'sn': 'LIC MF Tax Plan(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 8,
        'vn': 4,
        'vr': 3,
        'wl': 0,
        'y1': '5.04',
        'y3': '12.82',
        'y5': '12.08'
      },
      {
        'bm': 'Nifty 50 Arbitrage Index',
        'c': 2,
        'cc': '19',
        'cn': '13.06',
        'createdDate': '',
        'er': 1,
        'm6': '2.63',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 2166,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '0.5 % on or before 15 Days<br/> Nil after 15 Days<br/>',
        'sm': '1,000.00',
        'sn': 'Invesco India Arbitrage Fund(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 19,
        'vn': 8,
        'vr': 3,
        'wl': 0,
        'y1': '5.38',
        'y3': '5.79',
        'y5': '6.12'
      },
      {
        'bm': 'Nifty 50 Arbitrage Index',
        'c': 2,
        'cc': '19',
        'cn': '22.83',
        'createdDate': '',
        'er': 1,
        'm6': '2.91',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 2167,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '0.5 % on or before 15 Days<br/> Nil after 15 Days<br/>',
        'sm': '1,000.00',
        'sn': 'Invesco India Arbitrage Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 19,
        'vn': 8,
        'vr': 3,
        'wl': 0,
        'y1': '5.93',
        'y3': '6.00',
        'y5': '6.55'
      },
      {
        'bm': 'Nifty Midcap 100 - TRI',
        'c': 4,
        'cc': '32',
        'cn': '22.81',
        'createdDate': '',
        'er': 2.7,
        'm6': '7.02',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 2258,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil upto 1 % of units and 1% for above the limits on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'Invesco India Midcap Fund(D)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 32,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '0.57',
        'y3': '11.88',
        'y5': '13.74'
      },
      {
        'bm': 'Nifty Midcap 100 - TRI',
        'c': 4,
        'cc': '32',
        'cn': '48.87',
        'createdDate': '',
        'er': 2.7,
        'm6': '8.24',
        'mi': '1,000.00',
        'nr': 1,
        'sc': 2259,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'Nil upto 1 % of units and 1% for above the limits on or before 1 Year<br/> Nil after 1 Year<br/>',
        'sm': '1,000.00',
        'sn': 'Invesco India Midcap Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 32,
        'vn': 3,
        'vr': 3,
        'wl': 0,
        'y1': '1.73',
        'y3': '12.30',
        'y5': '13.97'
      },
      {
        'bm': 'NIFTY Medium to Long Term Debt Index',
        'c': 3,
        'cc': '68',
        'cn': '13.22',
        'createdDate': '',
        'er': 1.62,
        'm6': '9.73',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 2578,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '0.2 % on or before 15 Days<br/> Nil after 15 Days<br/>',
        'sm': '1,000.00',
        'sn': 'Reliance Income Fund(AD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 68,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '9.90',
        'y3': '5.90',
        'y5': '6.13'
      },
      {
        'bm': 'NIFTY Medium to Long Term Debt Index',
        'c': 3,
        'cc': '68',
        'cn': '60.96',
        'createdDate': '',
        'er': 1.62,
        'm6': '13.70',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 2580,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '0.2 % on or before 15 Days<br/> Nil after 15 Days<br/>',
        'sm': '1,000.00',
        'sn': 'Reliance Income Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 68,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '11.97',
        'y3': '7.67',
        'y5': '8.20'
      },
      {
        'bm': 'NIFTY Medium to Long Term Debt Index',
        'c': 3,
        'cc': '68',
        'cn': '12.91',
        'createdDate': '',
        'er': 1.62,
        'm6': '10.90',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 2581,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '0.2 % on or before 15 Days<br/> Nil after 15 Days<br/>',
        'sm': '1,000.00',
        'sn': 'Reliance Income Fund(HD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 68,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '10.04',
        'y3': '5.65',
        'y5': '6.10'
      },
      {
        'bm': 'NIFTY Medium to Long Term Debt Index',
        'c': 3,
        'cc': '68',
        'cn': '10.70',
        'createdDate': '',
        'er': 1.62,
        'm6': '11.32',
        'mi': '25,000.00',
        'nr': 1,
        'sc': 2582,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '0.2 % on or before 15 Days<br/> Nil after 15 Days<br/>',
        'sm': '1,000.00',
        'sn': 'Reliance Income Fund(MD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 68,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '9.96',
        'y3': '5.73',
        'y5': '6.03'
      },
      {
        'bm': 'NIFTY Medium to Long Term Debt Index',
        'c': 3,
        'cc': '68',
        'cn': '13.68',
        'createdDate': '',
        'er': 1.62,
        'm6': '11.76',
        'mi': '10,000.00',
        'nr': 1,
        'sc': 2583,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': '0.2 % on or before 15 Days<br/> Nil after 15 Days<br/>',
        'sm': '1,000.00',
        'sn': 'Reliance Income Fund(QD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 68,
        'vn': 1,
        'vr': 3,
        'wl': 0,
        'y1': '10.69',
        'y3': '5.66',
        'y5': '6.03'
      },
      {
        'bm': 'CRISIL Hybrid 85+15 - Conservative Index',
        'c': 4,
        'cc': '14',
        'cn': '43.31',
        'createdDate': '',
        'er': 1.84,
        'm6': '5.40',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 2649,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'NIL for 1 % of units on or before 12 Months<br/> 1% if exceeding 1 % of units on or before 12 Months<br/> Nil after 12 Months<br/>',
        'sm': '1,000.00',
        'sn': 'Reliance Hybrid Bond Fund(G)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 14,
        'vn': 7,
        'vr': 3,
        'wl': 0,
        'y1': '6.21',
        'y3': '7.14',
        'y5': '8.23'
      },
      {
        'bm': 'CRISIL Hybrid 85+15 - Conservative Index',
        'c': 4,
        'cc': '14',
        'cn': '11.84',
        'createdDate': '',
        'er': 1.84,
        'm6': '3.22',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 2650,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'NIL for 1 % of units on or before 12 Months<br/> 1% if exceeding 1 % of units on or before 12 Months<br/> Nil after 12 Months<br/>',
        'sm': '1,000.00',
        'sn': 'Reliance Hybrid Bond Fund(MD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 14,
        'vn': 7,
        'vr': 3,
        'wl': 0,
        'y1': '3.96',
        'y3': '4.93',
        'y5': '6.04'
      },
      {
        'bm': 'CRISIL Hybrid 85+15 - Conservative Index',
        'c': 4,
        'cc': '14',
        'cn': '12.52',
        'createdDate': '',
        'er': 1.84,
        'm6': '3.33',
        'mi': '5,000.00',
        'nr': 1,
        'sc': 2651,
        'schemeCode': 0,
        'schemeName': '',
        'si': 1,
        'sl': 'NIL for 1 % of units on or before 12 Months<br/> 1% if exceeding 1 % of units on or before 12 Months<br/> Nil after 12 Months<br/>',
        'sm': '1,000.00',
        'sn': 'Reliance Hybrid Bond Fund(QD)',
        'storyCode': 0,
        'storyHeadLine': '',
        'storyText': '',
        'sw': 'T',
        'tc': 1,
        'tot': '',
        'vc': 14,
        'vn': 7,
        'vr': 3,
        'wl': 0,
        'y1': '4.03',
        'y3': '4.93',
        'y5': '6.04'
      }
    ]
  ;
